-- MySQL
SELECT A.HOUR
     , COUNT(A.HOUR)
  FROM (
        SELECT DATE_FORMAT(DATETIME, '%H') AS HOUR
          FROM ANIMAL_OUTS
       ) A
 WHERE A.HOUR BETWEEN 9 AND 20
 GROUP
    BY A.HOUR
 ORDER
    BY A.HOUR